"""Grammar-constrained splice of historical fragments.

Valid fragments replace one field in a valid skeleton. Byte fragments
the grammar rejects are spliced only into malformed-probe slots.
Generated bytes are classified by the caller before they are stored.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field

from slip_lab.dialect import HEADER_MARK
from slip_lab.grammar import parse_tree, start_symbol


@dataclass(frozen=True)
class Fragment:
    nonterminal: str
    text: str
    malformed: bool
    source_id: str


@dataclass
class FragmentStore:
    by_nt: dict[str, list[Fragment]] = field(default_factory=dict)
    malformed: list[Fragment] = field(default_factory=list)

    def add(self, fragment: Fragment) -> None:
        if fragment.malformed:
            self.malformed.append(fragment)
            return
        self.by_nt.setdefault(fragment.nonterminal, []).append(fragment)


@dataclass(frozen=True)
class Splice:
    blob: bytes
    slot: str
    nonterminal: str
    parent_ids: tuple[str, ...]
    seed: int


def learn_fragments(items: list[tuple[str, bytes]]) -> FragmentStore:
    store = FragmentStore()
    for source_id, blob in items:
        tree = parse_tree(blob)
        if tree is None:
            store.add(Fragment("document", blob.decode("latin-1"), True, source_id))
            continue
        for record in tree["records"]:
            store.add(Fragment("record", record["text"], False, source_id))
            for child in record["children"]:
                store.add(Fragment(child["nt"], child["text"], False, source_id))
            store.add(Fragment("break", "\n", False, source_id))
    return store


def splice_field(skeleton: bytes, field_text: str, index: int) -> bytes:
    tree = parse_tree(skeleton)
    if tree is None:
        raise ValueError("skeleton is not in the record grammar")
    table = []
    flat: list[tuple[int, int]] = []
    for record_index, record in enumerate(tree["records"]):
        fields = [child["text"] for child in record["children"] if child["nt"] in {"field", "quoted_field"}]
        table.append(fields)
        for field_index in range(len(fields)):
            flat.append((record_index, field_index))
    if not flat:
        raise ValueError("skeleton has no fields")
    record_index, field_index = flat[index % len(flat)]
    table[record_index][field_index] = field_text
    lines = ["|".join(fields) for fields in table]
    return ("\n".join(lines) + "\n").encode("latin-1")


def first_data_field(skeleton: bytes) -> int:
    """Flat index of the first field after a header record, else 0."""

    tree = parse_tree(skeleton)
    if tree is None or not tree["records"]:
        return 0
    first = [child for child in tree["records"][0]["children"] if child["nt"] != "separator"]
    if first and first[0]["text"] == HEADER_MARK and len(tree["records"]) > 1:
        return len(first)
    return 0


def _slot(blob: bytes) -> str:
    return "valid" if parse_tree(blob) is not None else "malformed_probe"


def splice_malformed(skeleton: bytes, fragment_text: str) -> bytes:
    return (fragment_text + "\n" + skeleton.decode("latin-1")).encode("latin-1")


def as_splice(blob: bytes, slot: str, nonterminal: str, parent_ids: list[str], seed: int) -> Splice:
    return Splice(bytes(blob), slot, nonterminal, tuple(parent_ids), seed)


def mutate_delete_char(blob: bytes, rng: random.Random) -> bytes:
    if not blob:
        return blob
    index = rng.randrange(len(blob))
    return blob[:index] + blob[index + 1 :]


def mutate_add_field(blob: bytes, rng: random.Random) -> bytes:
    token = "Z" + str(rng.randrange(10))
    text = blob.decode("latin-1")
    trailing = text.endswith("\n")
    body = text[:-1] if trailing else text
    lines = body.split("\n") if body else [""]
    lines[-1] = lines[-1] + "|" + token
    return ("\n".join(lines) + "\n").encode("latin-1")


def generate_batch(sources: list[tuple[str, bytes]], seed: int) -> list[Splice]:
    """One historical quote splice, nearby edits, and one malformed probe."""

    rng = random.Random(seed)
    store = learn_fragments(sources)
    out: list[Splice] = []
    skeletons = [(source_id, blob) for source_id, blob in sources if parse_tree(blob) is not None]
    quote_frags = [
        fragment
        for fragment in store.by_nt.get("quoted_field", [])
        if '""' in fragment.text
    ]
    if quote_frags and skeletons:
        fragment = quote_frags[0]
        source_id, skeleton = skeletons[0]
        blob = splice_field(skeleton, fragment.text, first_data_field(skeleton))
        out.append(as_splice(blob, "valid", "quoted_field", [source_id, fragment.source_id], seed))
    if skeletons:
        source_id, skeleton = skeletons[0]
        for edited in (mutate_add_field(skeleton, rng), mutate_delete_char(skeleton, rng)):
            out.append(as_splice(edited, _slot(edited), "field", [source_id], seed))
        derived = _derive(rng, 2)
        out.append(as_splice(derived, "valid", "document", ["derive"], seed))
    host = skeletons[0][1] if skeletons else b"AA|BB\n"
    host_id = skeletons[0][0] if skeletons else "synthetic"
    probe = _safe_malformed(store)
    out.append(
        as_splice(
            splice_malformed(host, probe.text),
            "malformed_probe",
            probe.nonterminal,
            [host_id, probe.source_id],
            seed,
        )
    )
    return out


def _safe_malformed(store: FragmentStore) -> Fragment:
    """Prefer a learned fragment that cannot trip the legacy hang or byte crashes."""

    for fragment in store.malformed:
        if not fragment.text:
            continue
        if "\x00" in fragment.text or "\r" in fragment.text or "__HANG__" in fragment.text:
            continue
        return fragment
    return Fragment("quoted_field", '"NOEND', True, "synthetic")


def _derive(rng: random.Random, records: int) -> bytes:
    lines = []
    for _ in range(records):
        width = rng.randint(1, 3)
        fields = []
        for _field in range(width):
            length = rng.randint(1, 3)
            fields.append("".join(rng.choice("ABCDE123") for _char in range(length)))
        lines.append("|".join(fields))
    return ("\n".join(lines) + "\n").encode("latin-1")


def contexts_still_failing(parser, blobs: list[bytes]) -> list[bytes]:
    failing = []
    for blob in blobs:
        try:
            parser(blob)
        except Exception:
            failing.append(blob)
    return failing


def depth_rate(splices: list[Splice]) -> float:
    valid = [item for item in splices if item.slot == "valid"]
    if not valid:
        return 0.0
    hit = sum(1 for item in valid if start_symbol(item.blob) == "document")
    return hit / len(valid)
